name: Angular Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn and ng build
      run: |
        yarn
        npm run ng build --prod
        du -sh dist
      env:
        CI: true
      working-directory: .
