name: Angular Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - uses: actions@setup-node
      with:
        node-version: lts/*
    - name: yarn and ng test
      run: |
        yarn
        npm run ng test 
      env:
        CI: true
      working-directory: .
