name: Angular Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: yarn and ng test
      run: |
        yarn
        npm run ng test 
      env:
        CI: true
      working-directory: .
